module.exports = {
  content: ["../*.html", "../../design/**/*.html"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#311400",
        "inverse-on-surface": "#eff0fa",
        "surface-dim": "#d8d9e3",
        "tertiary-fixed": "#ffdcc6",
        "outline-variant": "#c2c6d6",
        "on-primary": "#ffffff",
        "inverse-surface": "#2e3038",
        "surface-container-highest": "#e1e2ec",
        "surface-tint": "#005ac2",
        background: "#f9f9ff",
        "primary-fixed-dim": "#adc6ff",
        outline: "#727785",
        "primary-container": "#2170e4",
        "on-primary-container": "#fefcff",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#b7c8e1",
        error: "#ba1a1a",
        "secondary-fixed": "#d3e4fe",
        "surface-container": "#ecedf7",
        primary: "#0058be",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e7f2",
        secondary: "#505f76",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e1e2ec",
        "on-surface-variant": "#424754",
        tertiary: "#924700",
        "secondary-container": "#d0e1fb",
        "on-primary-fixed-variant": "#004395",
        "on-tertiary-container": "#fffbff",
        "surface-bright": "#f9f9ff",
        "on-secondary-fixed": "#0b1c30",
        "on-secondary-container": "#54647a",
        "primary-fixed": "#d8e2ff",
        "tertiary-container": "#b75b00",
        "on-primary-fixed": "#001a42",
        "on-secondary-fixed-variant": "#38485d",
        "on-background": "#191b23",
        "inverse-primary": "#adc6ff",
        "on-surface": "#191b23",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#ffb786",
        "surface-container-low": "#f2f3fd",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#723600",
        surface: "#f9f9ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        xs: "4px",
        gutter: "20px",
        md: "16px",
        sm: "8px",
        xl: "40px",
        unit: "4px",
        lg: "24px",
        "container-max": "1440px",
      },
      fontFamily: {
        "headline-sm": ["Inter"],
        "label-md": ["Inter"],
        "headline-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"],
        "body-md": ["Inter"],
        "code-sm": ["monospace"],
      },
      fontSize: {
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
